
module.exports = {
    home_wrapper: {
        
    },
    home_header:{
        height:setWidth(60),
        fontSize:setFontSize(14),
        fontWeight:"bold",
        color:'red',
        backgroundColor:"#fff",
        dispaly:"flex",
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center"
    },
    myself_icon:{
        width:setWidth(54),
        height:setWidth(54)
    },
    input_wrapper:{
        dispaly:"flex",
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center",
        postion:"relative",
        borderWidth:1,
        borderColor:"#666",
    },
    search_icon:{
        width:setWidth(40),
        height:setWidth(40),
        marginLeft:setWidth(3)
    },
    input:{
        height:setWidth(56),
        width:setWidth(600),
        fontSize:setFontSize(18),
        paddingVertical: 0
    },
    map_wrapper:{
        backgroundColor:"#f1f1f1"
    },
    location_icon:{
        width:setWidth(40),
        height:setWidth(40),
        marginTop:setWidth(200),
        marginLeft:"auto",
        marginRight:"auto"
    },
    user_info_popup_wrapper:{
        position:"absolute",
        width:setWidth(600),
        left:"50%",
        top:setWidth(200),
        marginLeft:setWidth(-300),
        backgroundColor:"#fff",
        zIndex:999,
        dispaly:"flex",
        borderColor:gStyle.lineColor,
        borderWidth:1
    },
    user_img:{
        width:setWidth(120),
        height:setWidth(120),
        alignItems:"center",
        alignContent:"center",
        marginLeft:"auto",
        marginRight:"auto",
        marginTop:setWidth(50),
        marginBottom:setWidth(20)
    },
    user_info_text_wrapper:{
        dispaly:"flex",
    },
    user_info_text_item:{
        dispaly:"flex",
        flexDirection:"row",
        justifyContent:"flex-end"
    },
    text_item:{
        fontSize:setFontSize(15),
        textAlign:"left",
        width:setWidth(150),
        marginBottom:setWidth(10)
    },
    text_item_right:{
        marginRight:setWidth(70),
        width:setWidth(200),  
    },
    log_out_btn:{
        width:setWidth(250),
        backgroundColor:gStyle.btnBgColor,
        fontSize:setFontSize(16),
        color:"#fff",
        textAlign:"center",
        marginLeft:"auto",
        marginRight:"auto",
        marginBottom:setWidth(100),
        marginTop:setWidth(50),
        paddingTop:setWidth(15),
        paddingBottom:setWidth(15),
        // borderColor:"#000",
        // borderWidth:1,
        borderRadius:setWidth(5)
    },
    // 弹出菜单部分
    drawer_content_wrapper:{
        dispaly:"flex",
        flexDirection:"row"
    },
    drawer_content_left:{
        backgroundColor:gStyle.windowBgColor,
        width:gScreen.screen_width * 0.8,
        height:gScreen.screen_height
    },
    drawer_content_right:{
        backgroundColor:"rgba(0,0,0,0.3)",
        width:gScreen.screen_width * 0.2,
        height:gScreen.screen_height
    },
    drawer_content_head:{
        padding:setWidth(10),
        paddingBottom:0,
        color:"#fff"
    },
    drawer_img_wrapper:{
        dispaly:"flex",
        flexDirection:"row",
        justifyContent:"space-around",
        paddingTop:setWidth(20),
        paddingBottom:setWidth(20),
        borderColor:gStyle.lineColor,
        borderBottomWidth:1,
        borderTopWidth:1
    },
    drawer_content_text:{
        color:"#000",
        fontSize:setFontSize(16),
        marginBottom:setWidth(10),
        width:"100%"
    },
    text_align:{
        textAlign:"center",
        marginBottom:setWidth(0),
        marginTop:setWidth(10)
    },
    drawer_content_img:{
        width:setWidth(120),
        height:setWidth(120)
    },
    drawer_content_body:{
        padding:setWidth(10)
    },
    drawer_form_wrapper:{
        justifyContent:"flex-start",
        flexDirection:"column",
        paddingBottom:0,
        paddingTop:setWidth(40)
    },
    form_item:{
        dispaly:"flex",
        flexDirection:"row",
        alignItems:"center",
        marginBottom:setWidth(50)
    },
    form_item_text:{
        fontSize:setFontSize(16)
    },
    form_item_input:{
        borderColor:gStyle.lineColor,
        borderWidth:1,
        marginLeft:setWidth(10),
        width:setWidth(300),
        paddingVertical: 0,
        fontSize:setFontSize(16),
        paddingTop:setWidth(4),
        paddingBottom:setWidth(4)
    },
    // 查看定位信息模块
    location_info_wrapper:{
        backgroundColor:gStyle.windowBgColor,
        borderColor:gStyle.lineColor,
        borderWidth:1,
        width:setWidth(600),
        position:"absolute",
        top:setWidth(80),
        left:"50%",
        marginLeft:setWidth(-300),
        zIndex:888
    },
    location_info_img:{
        width:setWidth(600),
        height:setWidth(280)
    },
    location_info_item:{
        dispaly:"flex",
        flexDirection:"row",
        borderColor:gStyle.lineColor,
        borderWidth:1
    },
    location_info_text:{
        width:"50%",
        textAlign:"center",
        paddingTop:setWidth(8),
        paddingBottom:setWidth(8),
        borderColor:gStyle.lineColor,
        borderLeftWidth:1
    },
    shutdown_btn:{
        color:gStyle.btnBgColor,
        width:"100%",
        paddingTop:setWidth(4),
        paddingBottom:setWidth(4),
        paddingRight:setWidth(20),
        textAlign:"right",
        fontSize:setFontSize(30)
    }
}